//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinFormsUI.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang_nl {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang_nl() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinFormsUI.Languages.Lang_nl", typeof(Lang_nl).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There already is an address with description %s.
        /// </summary>
        internal static string AddressWithDescription {
            get {
                return ResourceManager.GetString("AddressWithDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back-up gemaakt.
        /// </summary>
        internal static string BackUpAndRestoreCreated {
            get {
                return ResourceManager.GetString("BackUpAndRestoreCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herstelbestand niet gevonden.
        /// </summary>
        internal static string BackUpAndRestoreNoRestoreFileExist {
            get {
                return ResourceManager.GetString("BackUpAndRestoreNoRestoreFileExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geen herstelbestand geselecteerd.
        /// </summary>
        internal static string BackUpAndRestoreNoRestoreFileSelected {
            get {
                return ResourceManager.GetString("BackUpAndRestoreNoRestoreFileSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herstel db-bestand.
        /// </summary>
        internal static string BackUpAndRestoreRestoreFile {
            get {
                return ResourceManager.GetString("BackUpAndRestoreRestoreFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecteer eerst een exportmap.
        /// </summary>
        internal static string BackUpAndRestoreSelectFile {
            get {
                return ResourceManager.GetString("BackUpAndRestoreSelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weet u zeker dat u deze prijs per eenheid wilt verwijderen?.
        /// </summary>
        internal static string CalculatedUnitPriceAskDelete {
            get {
                return ResourceManager.GetString("CalculatedUnitPriceAskDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vergelijk data per %s.
        /// </summary>
        internal static string ChartCompareTitle {
            get {
                return ResourceManager.GetString("ChartCompareTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vergelijk data per %s voor %m.
        /// </summary>
        internal static string ChartCompareTitleMonth {
            get {
                return ResourceManager.GetString("ChartCompareTitleMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gegevens per.
        /// </summary>
        internal static string ChartDefaultTitle {
            get {
                return ResourceManager.GetString("ChartDefaultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarieven.
        /// </summary>
        internal static string ChartRatesTitle {
            get {
                return ResourceManager.GetString("ChartRatesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gegevens zijn opgeslagen.
        /// </summary>
        internal static string DataSaved {
            get {
                return ResourceManager.GetString("DataSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dag.
        /// </summary>
        internal static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DeleteTitle {
            get {
                return ResourceManager.GetString("DeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beschrijving is een verplicht veld.
        /// </summary>
        internal static string DescriptionIsRequired {
            get {
                return ResourceManager.GetString("DescriptionIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestand bestaat al.
        /// </summary>
        internal static string FileAlreadyExists {
            get {
                return ResourceManager.GetString("FileAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestand bestaat al, wilt u overschrijven?.
        /// </summary>
        internal static string FileExistsOverWrite {
            get {
                return ResourceManager.GetString("FileExistsOverWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vast prijs.
        /// </summary>
        internal static string FixedPrice {
            get {
                return ResourceManager.GetString("FixedPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blader door importbestand.
        /// </summary>
        internal static string ImportBrowseFiles {
            get {
                return ResourceManager.GetString("ImportBrowseFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geselecteerd bestand bestaat niet of is niet toegankelijk.
        /// </summary>
        internal static string ImportSelectedFileNotExist {
            get {
                return ResourceManager.GetString("ImportSelectedFileNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecteer een bestand in om te importeren.
        /// </summary>
        internal static string ImportSelectFile {
            get {
                return ResourceManager.GetString("ImportSelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De huidige geselecteerde database in de configuratie bestaat niet of is niet toegankelijk, de database moet worden ingesteld voordat dit programma kan worden gebruikt..
        /// </summary>
        internal static string MainErrorDbNotExist {
            get {
                return ResourceManager.GetString("MainErrorDbNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database niet opgezet of niet toegankelijk, applicatie wordt gesloten..
        /// </summary>
        internal static string MainErrorDbNotSetup {
            get {
                return ResourceManager.GetString("MainErrorDbNotSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wilt u alle gegevens voor energietype &apos;%s&apos; opnieuw berekenen.
        /// </summary>
        internal static string MainRecalculate {
            get {
                return ResourceManager.GetString("MainRecalculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alles opnieuw berekenen.
        /// </summary>
        internal static string MainRecalculateAll {
            get {
                return ResourceManager.GetString("MainRecalculateAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maand.
        /// </summary>
        internal static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieuw adres.
        /// </summary>
        internal static string Newaddress {
            get {
                return ResourceManager.GetString("Newaddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieuwe categorie.
        /// </summary>
        internal static string Newcategory {
            get {
                return ResourceManager.GetString("Newcategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieuw energie type.
        /// </summary>
        internal static string Newenergytype {
            get {
                return ResourceManager.GetString("Newenergytype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieuwe meter.
        /// </summary>
        internal static string Newmeter {
            get {
                return ResourceManager.GetString("Newmeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieuwe periode.
        /// </summary>
        internal static string Newperiod {
            get {
                return ResourceManager.GetString("Newperiod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er is geen data om te exporteren.
        /// </summary>
        internal static string NoDataToExport {
            get {
                return ResourceManager.GetString("NoDataToExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aankoopbedrag moet groter zijn dan nul.
        /// </summary>
        internal static string PayBackTimeGreaterZero {
            get {
                return ResourceManager.GetString("PayBackTimeGreaterZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er is geen prijs per eenheid voor jaar %s.
        /// </summary>
        internal static string PayBackTimeNoPricePerUnit {
            get {
                return ResourceManager.GetString("PayBackTimeNoPricePerUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er zijn geen energietypes die energie teruggeven.
        /// </summary>
        internal static string PayBackTimeNoReturns {
            get {
                return ResourceManager.GetString("PayBackTimeNoReturns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het aankoopbedrag moet een numerieke waarde zijn.
        /// </summary>
        internal static string PayBackTimeShouldBeNumeric {
            get {
                return ResourceManager.GetString("PayBackTimeShouldBeNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het subsidiebedrag moet een numerieke waarde zijn.
        /// </summary>
        internal static string PayBackTimeSubsidyShouldBeNumeric {
            get {
                return ResourceManager.GetString("PayBackTimeSubsidyShouldBeNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weet je zeker dat je deze betaling wilt verwijderen?.
        /// </summary>
        internal static string PaymentAskDelete {
            get {
                return ResourceManager.GetString("PaymentAskDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voor gedefinieerde periodes.
        /// </summary>
        internal static string PredefinedDates {
            get {
                return ResourceManager.GetString("PredefinedDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voortgang.
        /// </summary>
        internal static string Progress {
            get {
                return ResourceManager.GetString("Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categorie wordt altijd berekend met tariefgroep: %s.
        /// </summary>
        internal static string RatesAlwaysCalculatedWith {
            get {
                return ResourceManager.GetString("RatesAlwaysCalculatedWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weet u zeker dat u dit tarief wilt verwijderen?.
        /// </summary>
        internal static string RatesAskDelete {
            get {
                return ResourceManager.GetString("RatesAskDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecteer een adres.
        /// </summary>
        internal static string SelectAddress {
            get {
                return ResourceManager.GetString("SelectAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecteer eerst een categorie.
        /// </summary>
        internal static string SelectCategory {
            get {
                return ResourceManager.GetString("SelectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecteer een energietype.
        /// </summary>
        internal static string SelectEnergyType {
            get {
                return ResourceManager.GetString("SelectEnergyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecteer een meter.
        /// </summary>
        internal static string SelectMeter {
            get {
                return ResourceManager.GetString("SelectMeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einddatum moet groot of gelijk zijn aan startdatum.
        /// </summary>
        internal static string SelectParametersEndDateLarger {
            get {
                return ResourceManager.GetString("SelectParametersEndDateLarger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecteer een adres om de afrekening voor te berekenen.
        /// </summary>
        internal static string SelectParametersSelectAddress {
            get {
                return ResourceManager.GetString("SelectParametersSelectAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecteer een tariefgroep.
        /// </summary>
        internal static string SelectTarifGroup {
            get {
                return ResourceManager.GetString("SelectTarifGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staffel.
        /// </summary>
        internal static string Staffel {
            get {
                return ResourceManager.GetString("Staffel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weet u zeker dat u deze tariefgroep wilt verwijderen?.
        /// </summary>
        internal static string TariffGroupsAskDelete {
            get {
                return ResourceManager.GetString("TariffGroupsAskDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieuwe group.
        /// </summary>
        internal static string TarifGroupNewGroup {
            get {
                return ResourceManager.GetString("TarifGroupNewGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weet u zeker dat u dit tarief wilt verwijderen?.
        /// </summary>
        internal static string ucDataDeleteRate {
            get {
                return ResourceManager.GetString("ucDataDeleteRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het huidige adres heeft geen meter voor %e.%nVoeg eerst een %e toe voordat u nieuwe meterregistraties registreert.
        /// </summary>
        internal static string ucDataNoMeter {
            get {
                return ResourceManager.GetString("ucDataNoMeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wilt u het huidige geselecteerde bereik voor energietype &apos;%s&apos; opnieuw berekenen?.
        /// </summary>
        internal static string ucDataRecalculate {
            get {
                return ResourceManager.GetString("ucDataRecalculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er zijn niet-opgeslagen wijzigingen. Weet u zeker dat u dit formulier wilt sluiten?.
        /// </summary>
        internal static string UnsavedChanges {
            get {
                return ResourceManager.GetString("UnsavedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niet-opgeslagen wijzigingen.
        /// </summary>
        internal static string UnsavedChangesTitle {
            get {
                return ResourceManager.GetString("UnsavedChangesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week.
        /// </summary>
        internal static string Week {
            get {
                return ResourceManager.GetString("Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jaar.
        /// </summary>
        internal static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
    }
}
