//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinFormsUI.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinFormsUI.Languages.Lang_en", typeof(Lang_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There already is an address with description %s.
        /// </summary>
        internal static string AddressWithDescription {
            get {
                return ResourceManager.GetString("AddressWithDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back-up created.
        /// </summary>
        internal static string BackUpAndRestoreCreated {
            get {
                return ResourceManager.GetString("BackUpAndRestoreCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No restore file does not exist.
        /// </summary>
        internal static string BackUpAndRestoreNoRestoreFileExist {
            get {
                return ResourceManager.GetString("BackUpAndRestoreNoRestoreFileExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No restore file selected.
        /// </summary>
        internal static string BackUpAndRestoreNoRestoreFileSelected {
            get {
                return ResourceManager.GetString("BackUpAndRestoreNoRestoreFileSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore db file.
        /// </summary>
        internal static string BackUpAndRestoreRestoreFile {
            get {
                return ResourceManager.GetString("BackUpAndRestoreRestoreFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please first select an export directory.
        /// </summary>
        internal static string BackUpAndRestoreSelectFile {
            get {
                return ResourceManager.GetString("BackUpAndRestoreSelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this unit price?.
        /// </summary>
        internal static string CalculatedUnitPriceAskDelete {
            get {
                return ResourceManager.GetString("CalculatedUnitPriceAskDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare data per %s.
        /// </summary>
        internal static string ChartCompareTitle {
            get {
                return ResourceManager.GetString("ChartCompareTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare data per %s for %m.
        /// </summary>
        internal static string ChartCompareTitleMonth {
            get {
                return ResourceManager.GetString("ChartCompareTitleMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data per.
        /// </summary>
        internal static string ChartDefaultTitle {
            get {
                return ResourceManager.GetString("ChartDefaultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rates.
        /// </summary>
        internal static string ChartRatesTitle {
            get {
                return ResourceManager.GetString("ChartRatesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data has been saved.
        /// </summary>
        internal static string DataSaved {
            get {
                return ResourceManager.GetString("DataSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        internal static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DeleteTitle {
            get {
                return ResourceManager.GetString("DeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description is a required field.
        /// </summary>
        internal static string DescriptionIsRequired {
            get {
                return ResourceManager.GetString("DescriptionIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File already exists.
        /// </summary>
        internal static string FileAlreadyExists {
            get {
                return ResourceManager.GetString("FileAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File already exists, do you want overwrite?.
        /// </summary>
        internal static string FileExistsOverWrite {
            get {
                return ResourceManager.GetString("FileExistsOverWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed price.
        /// </summary>
        internal static string FixedPrice {
            get {
                return ResourceManager.GetString("FixedPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse import file.
        /// </summary>
        internal static string ImportBrowseFiles {
            get {
                return ResourceManager.GetString("ImportBrowseFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected file does not exist or is not accessible.
        /// </summary>
        internal static string ImportSelectedFileNotExist {
            get {
                return ResourceManager.GetString("ImportSelectedFileNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a file to import.
        /// </summary>
        internal static string ImportSelectFile {
            get {
                return ResourceManager.GetString("ImportSelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current selected database in the config does not exist or is not accessible, the database needs to be set up before this program can be used..
        /// </summary>
        internal static string MainErrorDbNotExist {
            get {
                return ResourceManager.GetString("MainErrorDbNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database not set up or not accessible, application will be closed..
        /// </summary>
        internal static string MainErrorDbNotSetup {
            get {
                return ResourceManager.GetString("MainErrorDbNotSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to recalculate all data for energytype &apos;%s&apos;.
        /// </summary>
        internal static string MainRecalculate {
            get {
                return ResourceManager.GetString("MainRecalculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recalculate all.
        /// </summary>
        internal static string MainRecalculateAll {
            get {
                return ResourceManager.GetString("MainRecalculateAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        internal static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New address.
        /// </summary>
        internal static string Newaddress {
            get {
                return ResourceManager.GetString("Newaddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New category.
        /// </summary>
        internal static string Newcategory {
            get {
                return ResourceManager.GetString("Newcategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New energy type.
        /// </summary>
        internal static string Newenergytype {
            get {
                return ResourceManager.GetString("Newenergytype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New meter.
        /// </summary>
        internal static string Newmeter {
            get {
                return ResourceManager.GetString("Newmeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New period.
        /// </summary>
        internal static string Newperiod {
            get {
                return ResourceManager.GetString("Newperiod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data to export.
        /// </summary>
        internal static string NoDataToExport {
            get {
                return ResourceManager.GetString("NoDataToExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase amount should be greater then zero.
        /// </summary>
        internal static string PayBackTimeGreaterZero {
            get {
                return ResourceManager.GetString("PayBackTimeGreaterZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no price unit for year %s.
        /// </summary>
        internal static string PayBackTimeNoPricePerUnit {
            get {
                return ResourceManager.GetString("PayBackTimeNoPricePerUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no energy types that return energy.
        /// </summary>
        internal static string PayBackTimeNoReturns {
            get {
                return ResourceManager.GetString("PayBackTimeNoReturns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase amount should be a numeric value.
        /// </summary>
        internal static string PayBackTimeShouldBeNumeric {
            get {
                return ResourceManager.GetString("PayBackTimeShouldBeNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subsidy amount should be a numeric value.
        /// </summary>
        internal static string PayBackTimeSubsidyShouldBeNumeric {
            get {
                return ResourceManager.GetString("PayBackTimeSubsidyShouldBeNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this payment.
        /// </summary>
        internal static string PaymentAskDelete {
            get {
                return ResourceManager.GetString("PaymentAskDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to predefined dates.
        /// </summary>
        internal static string PredefinedDates {
            get {
                return ResourceManager.GetString("PredefinedDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        internal static string Progress {
            get {
                return ResourceManager.GetString("Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category is always calculated with tarif group: %s.
        /// </summary>
        internal static string RatesAlwaysCalculatedWith {
            get {
                return ResourceManager.GetString("RatesAlwaysCalculatedWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this rate?.
        /// </summary>
        internal static string RatesAskDelete {
            get {
                return ResourceManager.GetString("RatesAskDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an address.
        /// </summary>
        internal static string SelectAddress {
            get {
                return ResourceManager.GetString("SelectAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a category.
        /// </summary>
        internal static string SelectCategory {
            get {
                return ResourceManager.GetString("SelectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an energy type.
        /// </summary>
        internal static string SelectEnergyType {
            get {
                return ResourceManager.GetString("SelectEnergyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a meter.
        /// </summary>
        internal static string SelectMeter {
            get {
                return ResourceManager.GetString("SelectMeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date should be large or equal to start date.
        /// </summary>
        internal static string SelectParametersEndDateLarger {
            get {
                return ResourceManager.GetString("SelectParametersEndDateLarger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an address to calculate the settlement for.
        /// </summary>
        internal static string SelectParametersSelectAddress {
            get {
                return ResourceManager.GetString("SelectParametersSelectAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an tarif group.
        /// </summary>
        internal static string SelectTarifGroup {
            get {
                return ResourceManager.GetString("SelectTarifGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staffel.
        /// </summary>
        internal static string Staffel {
            get {
                return ResourceManager.GetString("Staffel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this tarif group?.
        /// </summary>
        internal static string TariffGroupsAskDelete {
            get {
                return ResourceManager.GetString("TariffGroupsAskDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New group.
        /// </summary>
        internal static string TarifGroupNewGroup {
            get {
                return ResourceManager.GetString("TarifGroupNewGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this rate?.
        /// </summary>
        internal static string ucDataDeleteRate {
            get {
                return ResourceManager.GetString("ucDataDeleteRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current address does not have a meter for %e.%nFirst add a %e before registering new meter registrations.
        /// </summary>
        internal static string ucDataNoMeter {
            get {
                return ResourceManager.GetString("ucDataNoMeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to recalculate current selected range for energytype &apos;%s&apos;?.
        /// </summary>
        internal static string ucDataRecalculate {
            get {
                return ResourceManager.GetString("ucDataRecalculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are unsaved changes are you sure you want to close this form?.
        /// </summary>
        internal static string UnsavedChanges {
            get {
                return ResourceManager.GetString("UnsavedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsaved changes.
        /// </summary>
        internal static string UnsavedChangesTitle {
            get {
                return ResourceManager.GetString("UnsavedChangesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week.
        /// </summary>
        internal static string Week {
            get {
                return ResourceManager.GetString("Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
    }
}
