name: Build and Publish WinForms App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'  # Specify the desired .NET version

      - name: Restore NuGet packages
        run: dotnet restore

      - name: Build WinForms app
        run: dotnet build --configuration Release

      - name: Run tests (if applicable)
        run: dotnet test

      - name: Create publish directory
        run: |
          mkdir -p publish
          cp -r bin/Release/net8.0/* publish/

      - name: Create installer (e.g., using Inno Setup)
        run: |
          # Install Inno Setup (if not already installed)
          choco install innosetup.portable -y
          
          # Create the installer script (modify as needed)
          echo '[Setup]' > myapp.iss
          echo 'AppName=EnergyUse' >> myapp.iss
          echo 'AppVersion=1.0' >> myapp.iss
          echo 'OutputBaseFilename=EnergyUseInstaller' >> myapp.iss
          echo 'OutputDir=publish' >> myapp.iss
          echo 'SourceDir=publish' >> myapp.iss
          echo 'ArchitecturesInstallIn64BitMode=x64' >> myapp.iss
          echo 'DefaultDirName={pf}\EnergyUse' >> myapp.iss
          echo 'DisableDirPage=yes' >> myapp.iss
          echo 'DisableProgramGroupPage=yes' >> myapp.iss
          echo 'UninstallDisplayIcon={app}\EnergyUse.exe' >> myapp.iss
          echo 'UninstallDisplayName=EnergyUse' >> myapp.iss
          echo 'UninstallFilesDir={app}' >> myapp.iss
          echo 'UninstallLogMode=append' >> myapp.iss
          echo 'UninstallStyle=classic' >> myapp.iss

          # Compile the installer
          iscc myapp.iss

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: energyuse-artifacts
          path: publish
